on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - uses: pujux/argocd-manifest-update@v0.1
        with:
          deployment-repo: "pujux/argocd-manifest-update-deployment-test"
          github-token: ${{ secrets.TEST_GITHUB_TOKEN }}
          deployment-repo-ref: "master"
          manifest-file: "apps/test.yml"
          image-name: "pujux-test"
          image-tag: "1.0"